spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    url: jdbc:mysql://localhost:3306/inventory-service?useSSL=false&allowPublicKeyRetrieval=true
    password: "root"
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop # later use liquibase

server:
  port: 8082
